//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ComplaintId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> TargetBookId { get; set; }
        public Nullable<int> TargetReviewId { get; set; }
        public string Reason { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Book Book { get; set; }
        public virtual Review Review { get; set; }
    }
}
