//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP01
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadingList
    {
        public int ListId { get; set; }
        public int UserId { get; set; }
        public int BookId { get; set; }
        public string Section { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Book Book { get; set; }
    }
}
